transporteescolar/choferes/urls.py
from django.urls import path
from . import views

app_name = "choferes"

urlpatterns = [
    path('registrar_chofer/', views.registrar_chofer, name='registrar_chofer'),
    path('', views.listar_choferes, name='listar_choferes'),
    path('editar_chofer/<int:id>/', views.editar_chofer, name='editar_chofer'),
    path('eliminar_chofer/<int:id>/',
         views.eliminar_chofer, name='eliminar_chofer'),

]

transporteescolar/establecimientos/urls.py
from django.urls import path
from . import views

app_name = "establecimientos"
urlpatterns = [
    path('registrar_establecimiento/', views.registrar_establecimiento,
         name='registrar_establecimiento'),
    path('', views.listar_establecimientos, name='listar_establecimientos'),
    path('editar_establecimiento/<int:id>/',
         views.editar_establecimiento, name='editar_establecimiento'),
    path('eliminar_establecimiento/<int:id>/',
         views.eliminar_establecimiento, name='eliminar_establecimiento'),
]

transporteescolar/furgones/urls.py
from django.urls import path
from . import views

app_name = "furgones"

urlpatterns = [
    path('registrar_furgon/', views.registrar_furgon, name='registrar_furgon'),
    path('', views.listar_furgones, name='listar_furgones'),
    path('editar_furgon/<int:pk>/', views.editar_furgon, name='editar_furgon'),
    path('eliminar_furgon/<int:pk>/',
         views.eliminar_furgon, name='eliminar_furgon'),
]

transporteescolar/transporteescolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.pagina_inicio),
    path('usuarios/', include('usuarios.urls')),
    path('choferes/', include('choferes.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('furgones/', include('furgones.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transporteescolar/usuarios/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
]

transporteescolar/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Transporte, Escolar" />
    <meta name="description" content="App de gestion de transporte escolar" />
    <link rel="shortcut icon"
          type="image/x-icon"
          href="{% static 'imgs/favicon.ico' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/bootstrap-table.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
          integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD"
          crossorigin="anonymous">
    <script src="{% static 'js/principal.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.29.0/tableExport.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.29.0/libs/jsPDF/jspdf.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/bootstrap-table.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/bootstrap-table-locale-all.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/transporte.css' %}">
    <!-- Bootstrap Datepicker CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
          rel="stylesheet">
    <!-- Bootstrap Datepicker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.es.min.js"></script>
    <!-- Moment.js (requerido por Tempus Dominus) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <!-- Popperjs -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <!-- Tempus Dominus JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.9.4/dist/js/tempus-dominus.min.js"
            crossorigin="anonymous"></script>
    <!-- Tempus Dominus Styles -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.9.4/dist/css/tempus-dominus.min.css"
          crossorigin="anonymous">
    <title>
      {% block title %}
        Transporte Escolar
      {% endblock title %}
    </title>
  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-lg bg-dark border-bottom border-body"
         data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Transportes Escolares</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"
                     href="#"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false">Usuarios</a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="nav-link" href="{% url 'usuarios:registro' %}">Crear Usuario</a>
                    </li>
                  </ul>
                </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">Choferes</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="nav-link" href="{% url 'choferes:listar_choferes' %}">Choferes</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">Establecimientos</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="nav-link"
                       href="{% url 'establecimientos:listar_establecimientos' %}">Establecimientos</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">Furgones</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="nav-link" href="{% url 'furgones:listar_furgones' %}">Furgones</a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link link-info" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
              </li>
            {% endif %}
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">Opciones</a>
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:perfil' %}">Mi perfil</a>
                  </li>
                  <li>
                    <li class="nav-item">
                      <a class="nav-link link-danger "
                         href="#"
                         onclick="document.getElementById('logout-form').submit();">Cerrar Sesión</a>
                    </li>
                    <form id="logout-form"
                          action="{% url 'usuarios:logout' %}"
                          method="post"
                          style="display: none">
                      {% csrf_token %}
                    </form>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <main>
        <div class="container-fluid">
          {% block content %}{% endblock %}
        </div>
      </main>
      {% if messages %}
        {% for message in messages %}<script>mensaje(' {{ message }}', '{{message.tags}}')</script>{% endfor %}
      {% endif %}
      {% include "footer.html" %}

transporteescolar/templates/footer.html
<footer> 
    <center>Hecho en Chile por @cfuentes</center>
    <center>Contacto: christian.fuentes@docentes.cftsa.cl</center>
  </footer> 
  </body> 
  </html>

transporteescolar/templates/inicio.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Transporte Escolar
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="header">
            <h1>Bienvenidos a Transporte Escolar</h1>
        </div>
        <div class="image-frame">
            <img src="{% static 'imgs/transporte.png' %}" width="400"
                 alt="Imagen de Transporte Escolar">
        </div>
        <div class="content">
            <p>
                Ofrecemos servicios de transporte escolar seguros y confiables para tus hijos. Nuestro compromiso es garantizar la seguridad y comodidad en cada viaje.
            </p>
        </div>
    </div>
{% endblock content %}