transporteescolar/choferes/urls.py
from django.urls import path
from . import views

app_name = "choferes"

urlpatterns = [
    path('registrar_chofer/', views.registrar_chofer, name='registrar_chofer'),
    path('', views.listar_choferes, name='listar_choferes'),
    path('editar_chofer/<int:id>/', views.editar_chofer, name='editar_chofer'),
    path('eliminar_chofer/<int:id>/',
         views.eliminar_chofer, name='eliminar_chofer'),

]

transporteescolar/furgones/urls.py
from django.urls import path
from . import views

app_name = "furgones"

urlpatterns = [
    path('registrar_furgon/', views.registrar_furgon, name='registrar_furgon'),
    path('', views.listar_furgones, name='listar_furgones'),
    path('editar_furgon/<int:pk>/', views.editar_furgon, name='editar_furgon'),
    path('eliminar_furgon/<int:pk>/',
         views.eliminar_furgon, name='eliminar_furgon'),
]

transporteescolar/transporteescolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.pagina_inicio),
    path('usuarios/', include('usuarios.urls')),
    path('choferes/', include('choferes.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('furgones/', include('furgones.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transporteescolar/furgones/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator
from django.db.models.signals import m2m_changed
from establecimientos.models import Establecimiento
from django.core.exceptions import ValidationError
from choferes.models import Chofer
import re


class Furgon(models.Model):
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('I', 'Inactivo'),
    ]

    def validate_patente(value):
        if not re.match(r'^[BCDFGHJKLMNPQRSTVWXYZ]{4}\d{2}$', value):
            raise ValidationError(
                '%(value)s no es un formato de patente válido. Debe ser de 4 letras (sin vocales) seguidas de 2 números.',
                params={'value': value},
            )

    patente = models.CharField(
        max_length=6, unique=True, validators=[validate_patente])
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    año = models.PositiveIntegerField(
        validators=[MinValueValidator(2010), MaxValueValidator(2050)])
    estado = models.CharField(
        max_length=1, choices=ESTADO_CHOICES, default='A')
    chofer_asignado = models.ForeignKey(
        Chofer, on_delete=models.SET_NULL, null=True, blank=True)
    establecimientos = models.ManyToManyField(
        Establecimiento, blank=True)

    def __str__(self):
        return self.patente

transporteescolar/furgones/forms.py
from django import forms
from .models import Furgon
from django.core.exceptions import ValidationError
import datetime


class FurgonForm(forms.ModelForm):
    class Meta:
        model = Furgon
        fields = ['patente', 'marca', 'modelo', 'año',
                  'chofer_asignado', 'establecimientos']
        widgets = {
            'establecimientos': forms.CheckboxSelectMultiple(),
        }

    def clean_establecimientos(self):
        establecimientos = self.cleaned_data.get('establecimientos')
        if establecimientos and establecimientos.count() > 2:
            raise ValidationError(
                "Un furgón no puede estar asociado a más de dos establecimientos.")
        return establecimientos

    def clean_año(self):
        año = self.cleaned_data.get('año')
        hoy = datetime.date.today()
        año_tope = hoy.year + 1
        if año > año_tope:
            raise ValidationError(
                f"El año no puede ser superior al {año_tope} .")
        return año

transporteescolar/furgones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Furgon
from .forms import FurgonForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url="/usuarios/login")
def registrar_furgon(request):
    if request.method == 'POST':
        form = FurgonForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Furgón registrado exitosamente.')
            return redirect('furgones:listar_furgones')
    else:
        form = FurgonForm()
    return render(request, 'furgones/registrar_furgon.html', {'form': form})


@login_required(login_url="/usuarios/login")
def listar_furgones(request):
    furgones = Furgon.objects.all()
    return render(request, 'furgones/listar_furgones.html', {'furgones': furgones})


@login_required(login_url="/usuarios/login")
def editar_furgon(request, pk):
    furgon = get_object_or_404(Furgon, pk=pk)
    if request.method == 'POST':
        form = FurgonForm(request.POST, instance=furgon)
        if form.is_valid():
            form.save()
            messages.success(request, 'Furgón actualizado exitosamente.')
            return redirect('furgones:listar_furgones')
    else:
        form = FurgonForm(instance=furgon)
    return render(request, 'furgones/editar_furgon.html', {'form': form, 'furgon': furgon})


@login_required(login_url="/usuarios/login")
def eliminar_furgon(request, pk):
    furgon = get_object_or_404(Furgon, pk=pk)
    if request.method == 'POST':
        furgon.delete()
        messages.success(request, 'Furgón eliminado exitosamente.')
        return redirect('furgones:listar_furgones')
    return render(request, 'furgones/eliminar_furgon.html', {'furgon': furgon})

transporteescolar/furgones/templates/furgones/editar_furgon.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Furgon
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Editar Furgon</h1>
                <form action="{% url 'furgones:editar_furgon' furgon.id %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-success">Editar Furgon</button>
                        <a href="{% url 'furgones:listar_furgones' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>

                    
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}

transporteescolar/furgones/templates/furgones/eliminar_furgon.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Eliminar Furgon
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Eliminar Furgon</h1>
                <p>
                    <p>¿Estás seguro de que deseas eliminar el furgón con patente {{ furgon.patente }}?</p>
                </p>
                <form action="{% url 'furgones:eliminar_furgon' furgon.id %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-danger">Eliminar Furgon</button>
                        <a href="{% url 'furgones:listar_furgones' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}

transporteescolar/furgones/templates/furgones/listar_furgones.html
{% extends "base.html" %}
{% block title %}
    Listado de Furgones
{% endblock title %}
{% block content %}
    <div class="container">
        <h1>Listado de Furgones</h1>
        <button class="btn btn-primary mb-3"
                onclick="window.location.href='{% url 'furgones:registrar_furgon' %}'">Registrar Furgon</button>
        <div class="row">
            <table id="table"
                   data-show-export="true"
                   data-pagination="true"
                   data-click-to-select="true"
                   data-show-toggle="true"
                   data-show-columns="true"
                   data-search="true">
            </table>
        </div>
    </div>
    <script>
    var $table = $('#table')
    $(function () {
        function operateFormatter(value, row, index) {
            let editar = '<button class="btn btn-warning btn-sm editar" href="javascript:void(0)" title="Editar">Editar</button>&nbsp;&nbsp;'
            let eliminar = '<button class="btn btn-danger btn-sm eliminar" href="javascript:void(0)" title="Eliminar">Eliminar</button>&nbsp;&nbsp;'
            return [editar, eliminar].join('');
          }
        
          window.operateEvents = {
            'click .editar': function (e, value, row, index) {
                window.location.href = "{% url 'furgones:editar_furgon' 0 %}".replace('0', row.id);
            },
            'click .eliminar': function (e, value, row, index) {
                window.location.href = "{% url 'furgones:eliminar_furgon' 0 %}".replace('0', row.id);
            }
          }

      var data = [{% for furgon in furgones %}
        {   id:"{{ furgon.id }}",
            patente:"{{ furgon.patente }}",
            marca_modelo:"{{ furgon.marca }} - {{ furgon.modelo }}",
            año: "{{ furgon.año }}",
            estado: "{{ furgon.get_estado_display }}",
            chofer_asignado: "{{ furgon.chofer_asignado }}",
            establecimientos: "{% for establecimiento in furgon.establecimientos.all %}{{ establecimiento.nombre }}{% if not forloop.last %}, {% endif %}{% endfor %}",
            operate: "Detalle"
        },
        {% endfor %}
        ]


           function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
              height: 550,
              locale: "es-cl",
              data: data,
              classes:"table table-striped table-dark table-fit table-bordered table-hover",
              columns: [
                [{
                  field: 'id',
                  title: 'id',
                  visible: false,
                  align: 'center'
                },{
                    field: 'patente',
                    title: 'Patente',
                    visible: true,
                    align: 'center'
                  },{
                    field: 'marca_modelo',
                    title: 'Marca - Modelo',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'año',
                    title: 'Año',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'estado',
                    title: 'Estado',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'chofer_asignado',
                    title: 'Chofer Asignado',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'establecimientos',
                    title: 'Establecimientos',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'operate',
                    title: 'Detalle',
                    align: 'center',
                    clickToSelect: false,
                    events: window.operateEvents,
                    formatter: operateFormatter
                  }
                ]
              ]
            })
          
        }

        
      
      initTable()
    })

    </script>
{% endblock content %}

transporteescolar/furgones/templates/furgones/registrar_furgon.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Registrar Furgon
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Registrar Furgon</h1>
                <form action="{% url 'furgones:registrar_furgon' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-success">Registrar Furgon</button>
                        <a href="{% url 'furgones:listar_furgones' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>

                    
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}