transporteescolar/choferes/urls.py
from django.urls import path
from . import views

app_name = "choferes"

urlpatterns = [
    path('registrar_chofer/', views.registrar_chofer, name='registrar_chofer'),
    path('', views.listar_choferes, name='listar_choferes'),
    path('editar_chofer/<int:id>/', views.editar_chofer, name='editar_chofer'),
    path('eliminar_chofer/<int:id>/',
         views.eliminar_chofer, name='eliminar_chofer'),

]

transporteescolar/transporteescolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.pagina_inicio),
    path('usuarios/', include('usuarios.urls')),
    path('choferes/', include('choferes.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('furgones/', include('furgones.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transporteescolar/choferes/models.py
from django.db import models
from establecimientos.models import Comuna
from django.core.validators import RegexValidator


class Chofer(models.Model):
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('I', 'Inactivo'),
    ]

    DV_CHOICES = [(str(i), str(i)) for i in range(10)] + [('K', 'K')]

    rut = models.PositiveIntegerField(
        unique=True,
        validators=[RegexValidator(
            regex=r'^\d{7,8}$', message='El RUT debe tener entre 7 y 8 dígitos')]
    )
    dv = models.CharField(max_length=1, choices=DV_CHOICES)
    nombres = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    direccion = models.CharField(max_length=255)
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True)
    telefono = models.CharField(max_length=9)
    # telefono = models.CharField(
    #     max_length=12,
    #     validators=[RegexValidator(
    #         regex=r'^\+56\d{9}$', message='El teléfono debe tener el formato +56XXXXXXXXX')],
    #     default=None
    # )
    email = models.EmailField(default=None)
    estado = models.CharField(
        max_length=1, choices=ESTADO_CHOICES, default='A')

    def __str__(self):
        return f"{self.nombres} {self.apellido_paterno} {self.apellido_materno}"

transporteescolar/choferes/forms.py
from django import forms
from .models import Chofer
from django.core.exceptions import ValidationError
import re


class ChoferForm(forms.ModelForm):
    class Meta:
        model = Chofer
        fields = ['rut', 'dv', 'nombres', 'apellido_paterno', 'apellido_materno',
                  'fecha_nacimiento', 'direccion', 'comuna', 'telefono', 'email']
        # widgets = {
        #     'fecha_nacimiento': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
        # }
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'id': 'id_fecha_nacimiento', 'class': 'd-none'}),

        }
    rut = forms.CharField(
        max_length=8
    )
    telefono = forms.CharField(
        max_length=9,
        help_text="Ingrese 9 dígitos"
    )

    def clean_telefono(self):
        telefono = self.cleaned_data.get('telefono')
        if not re.match(r'^\d{9}$', telefono):
            raise ValidationError(
                "El número de teléfono debe tener 9 dígitos.")
        return telefono

transporteescolar/choferes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Chofer
from .forms import ChoferForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url="/usuarios/login")
def registrar_chofer(request):
    if request.method == 'POST':
        form = ChoferForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Chofer registrado exitosamente.')
            return redirect('choferes:listar_choferes')
    else:
        form = ChoferForm()
    return render(request, 'choferes/registrar_chofer.html', {'form': form})


@login_required(login_url="/usuarios/login")
def listar_choferes(request):
    choferes = Chofer.objects.all()
    return render(request, 'choferes/listar_choferes.html', {'choferes': choferes})


@login_required(login_url="/usuarios/login")
def editar_chofer(request, id):
    chofer = get_object_or_404(Chofer, id=id)
    if request.method == 'POST':
        form = ChoferForm(request.POST, instance=chofer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Chofer actualizado exitosamente.')
            return redirect('choferes:listar_choferes')
    else:
        form = ChoferForm(instance=chofer)
    return render(request, 'choferes/editar_chofer.html', {'form': form, 'chofer': chofer})


@login_required(login_url="/usuarios/login")
def eliminar_chofer(request, id):
    chofer = get_object_or_404(Chofer, id=id)
    if request.method == 'POST':
        chofer.delete()
        messages.success(request, 'Chofer eliminado exitosamente.')
        return redirect('choferes:listar_choferes')
    return render(request, 'choferes/eliminar_chofer.html', {'chofer': chofer})

transporteescolar/choferes/templates/choferes/editar_chofer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Chofer
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Editar Chofer</h1>
                <form id="choferForm"
                      action="{% url 'choferes:editar_chofer' chofer.id %}"
                      method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.rut|as_crispy_field }}
                    {{ form.dv|as_crispy_field }}
                    {{ form.nombres|as_crispy_field }}
                    {{ form.apellido_paterno|as_crispy_field }}
                    {{ form.apellido_materno|as_crispy_field }}
                    <div class="form-group">
                        <label for="id_fecha_nacimiento">Fecha Nacimiento</label>
                        <input type="text" class="form-control" id="datepicker">
                    </div>
                    <br>
                    {{ form.direccion|as_crispy_field }}
                    {{ form.comuna|as_crispy_field }}
                    {{ form.telefono|as_crispy_field }}
                    {{ form.email|as_crispy_field }}
                    <input type="hidden"
                           id="id_fecha_nacimiento"
                           name="fecha_nacimiento"
                           value="{{ chofer.fecha_nacimiento|date:'Y-m-d' }}">
                    <center>
                        <button class="btn btn-success">Editar Chofer</button>
                        <a href="{% url 'choferes:listar_choferes' %}" class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
           
            function adjustDate(date) {
                var d = new Date(date);
                d.setMinutes(d.getMinutes() + d.getTimezoneOffset());
                var month = '' + (d.getMonth() + 1);
                var day = '' + d.getDate();
                var year = d.getFullYear();

                if (month.length < 2) month = '0' + month;
                if (day.length < 2) day = '0' + day;

                return [day, month, year].join('/');
            }

            var fechaNacimiento = '{{ chofer.fecha_nacimiento|date:"Y-m-d" }}';
            console.log(fechaNacimiento)
            var adjustedDate = adjustDate(fechaNacimiento);
            console.log(adjustedDate)

            $('#datepicker').datepicker({
                format: 'dd/mm/yyyy',
                autoclose: true,
                language: 'es'
            }).datepicker('setDate', adjustedDate).on('changeDate', function(e) {
                $('#id_fecha_nacimiento').val(e.format('yyyy-mm-dd'));
            });

            $('#choferForm').on('submit', function() {
                var selectedDate = $('#datepicker').datepicker('getFormattedDate', 'yyyy-mm-dd');
                $('#id_fecha_nacimiento').val(selectedDate);
            });
        });
    </script>
{% endblock content %}

transporteescolar/choferes/templates/choferes/eliminar_chofer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Eliminar Chofer
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Eliminar Chofer</h1>
                <p>
                    ¿Estás seguro de que deseas eliminar al chofer {{ chofer.nombres }} {{ chofer.apellido_paterno }} {{ chofer.apellido_materno }}?
                </p>
                <form action="{% url 'choferes:eliminar_chofer' chofer.id %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-danger">Eliminar Chofer</button>
                        <a href="{% url 'choferes:listar_choferes' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}

transporteescolar/choferes/templates/choferes/listar_choferes.html
{% extends "base.html" %}
{% block title %}
    Listado de Choferes
{% endblock title %}
{% block content %}
    <div class="container">
        <h1>Listado de Choferes</h1>
        <button class="btn btn-primary mb-3"
                onclick="window.location.href='{% url 'choferes:registrar_chofer' %}'">Registrar Nuevo Chofer</button>
        <div class="row">
            <table id="table"
            data-show-export="true"
            data-pagination="true"
            data-click-to-select="true"
            data-show-toggle="true"
            data-show-columns="true"
            data-search="true"
            >
          </table>
        </div>
    </div>


<script>
    var $table = $('#table')
    $(function () {
        function operateFormatter(value, row, index) {
            let editar = '<button class="btn btn-warning btn-sm editar" href="javascript:void(0)" title="Editar">Editar</button>&nbsp;&nbsp;'
            let eliminar = '<button class="btn btn-danger btn-sm eliminar" href="javascript:void(0)" title="Eliminar">Eliminar</button>&nbsp;&nbsp;'
            return [editar, eliminar].join('');
          }
        
          window.operateEvents = {
            /*'click .editar': function (e, value, row, index) {
                miid=row.id
              window.location.href="/choferes/editar_chofer/"+miid+"/"
            },*/
            'click .editar': function (e, value, row, index) {
                window.location.href = "{% url 'choferes:editar_chofer' 0 %}".replace('0', row.id);
            },
            /*'click .eliminar': function (e, value, row, index) {
              miid=row.id
              const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

              $.ajax({
                headers: {'X-CSRFToken' : csrftoken},
                method: "POST",
                url: "eliminar_anuncio/"+miid+"/",
              })
              .done(function( msg ) {
                window.location.href="/anuncios/otrolistar"
              });


            },*/
            'click .eliminar': function (e, value, row, index) {
                window.location.href = "{% url 'choferes:eliminar_chofer' 0 %}".replace('0', row.id);
            }
          }

      var data = [{% for chofer in choferes %}
        {   id:"{{ chofer.id }}",
            rut:"{{ chofer.rut }}-{{ chofer.dv }}",
            nombres:"{{ chofer.nombres }}",
            apellido_paterno: "{{ chofer.apellido_paterno }}",
            apellido_materno: "{{ chofer.apellido_materno }}",
            comuna: "{{ chofer.comuna.nombre }}",
            estado: "{{ chofer.get_estado_display }}",
            operate: "Detalle"
        },
        {% endfor %}
        ]


           function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
              height: 550,
              locale: "es-cl",
              data: data,
              columns: [
                [{
                  field: 'id',
                  title: 'id',
                  visible: false,
                  align: 'center'
                },{
                    field: 'rut',
                    title: 'Rut',
                    visible: false,
                    align: 'center'
                  },{
                    field: 'nombres',
                    title: 'Nombres',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'apellido_paterno',
                    title: 'Apellido Paterno',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'apellido_materno',
                    title: 'Apellido Materno',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'comuna',
                    title: 'Comuna',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'estado',
                    title: 'Estado',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'operate',
                    title: 'Detalle',
                    align: 'center',
                    clickToSelect: false,
                    events: window.operateEvents,
                    formatter: operateFormatter
                  }
                ]
              ]
            })
          
        }

        
      
      initTable()
    })

</script>
{% endblock content %}

transporteescolar/choferes/templates/choferes/registrar_chofer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Registrar Chofer
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Registrar Chofer</h1>
                <form id="choferForm" action="{% url 'choferes:registrar_chofer' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.rut|as_crispy_field }}
                    {{ form.dv|as_crispy_field }}
                    {{ form.nombres|as_crispy_field }}
                    {{ form.apellido_paterno|as_crispy_field }}
                    {{ form.apellido_materno|as_crispy_field }}
                    <div class="form-group">
                        <label for="datepicker">Fecha de Nacimiento</label>
                        <div class="input-group date" id="datepicker" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" data-target="#datepicker"/>
                        </div>
                    </div>
                    <br>
                    {{ form.direccion|as_crispy_field }}
                    {{ form.comuna|as_crispy_field }}
                    {{ form.telefono|as_crispy_field }}
                    {{ form.email|as_crispy_field }}
                    
                    <input type="hidden" id="id_fecha_nacimiento" name="fecha_nacimiento">
                   
                    <center>
                        <button class="btn btn-success">Registrar Chofer</button>
                        <a href="{% url 'choferes:listar_choferes' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            // Inicializar Tempus Dominus
            var datepicker = new tempusDominus.TempusDominus(document.getElementById('datepicker'), {
                display: {
                    components: {
                        calendar: true,
                        date: true,
                        month: true,
                        year: true,
                        decades: true,
                        clock: false,
                        hours: false,
                        minutes: false,
                        seconds: false
                    },
                    buttons: {
                        today: true,
                        clear: true,
                        close: true
                    }
                },
                localization: {
                    locale: 'es'
                }
            });

            datepicker.dates.formatInput = function(date) { {return moment(date).format('DD/MM/YYYY') } }

            document.getElementById('datepicker').addEventListener('change.td', function(e) {
                var selectedDate = moment(e.detail.date).format('YYYY-MM-DD');
                document.getElementById('id_fecha_nacimiento').value = selectedDate;
            });

            $('#choferForm').on('submit', function() {
                var selectedDate = moment(datepicker.dates.lastPicked).format('YYYY-MM-DD');
                console.log(selectedDate)
                $('#id_fecha_nacimiento').val(selectedDate);
            });
        });
    </script>

    <script>
        /*  //Opcion 2: Usar datepicker
            $(document).ready(function(){
            $('#datepicker').datepicker({
                format: 'dd/mm/yyyy',
                autoclose: true,
                language: 'es'
            }).on('changeDate', function(e) {
                $('#id_fecha_nacimiento').val(e.format('yyyy-mm-dd'));
            });
            $('#choferForm').on('submit', function() {
                $('#id_fecha_nacimiento').val($('#datepicker').val());
            });
        });*/
    </script>
{% endblock content %}