transporteescolar/choferes/urls.py
from django.urls import path
from . import views

app_name = "choferes"

urlpatterns = [
    path('registrar_chofer/', views.registrar_chofer, name='registrar_chofer'),
    path('', views.listar_choferes, name='listar_choferes'),
    path('editar_chofer/<int:id>/', views.editar_chofer, name='editar_chofer'),
    path('eliminar_chofer/<int:id>/',
         views.eliminar_chofer, name='eliminar_chofer'),

]

transporteescolar/establecimientos/urls.py
from django.urls import path
from . import views

app_name = "establecimientos"
urlpatterns = [
    path('registrar_establecimiento/', views.registrar_establecimiento,
         name='registrar_establecimiento'),
    path('', views.listar_establecimientos, name='listar_establecimientos'),
    path('editar_establecimiento/<int:id>/',
         views.editar_establecimiento, name='editar_establecimiento'),
    path('eliminar_establecimiento/<int:id>/',
         views.eliminar_establecimiento, name='eliminar_establecimiento'),
]

transporteescolar/transporteescolar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.pagina_inicio),
    path('usuarios/', include('usuarios.urls')),
    path('choferes/', include('choferes.urls')),
    path('establecimientos/', include('establecimientos.urls')),
    path('furgones/', include('furgones.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transporteescolar/establecimientos/models.py
from django.db import models


class Establecimiento(models.Model):
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('I', 'Inactivo'),
    ]

    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=9)
    comuna = models.ForeignKey('Comuna', on_delete=models.SET_NULL, null=True)
    email = models.EmailField()
    estado = models.CharField(
        max_length=1, choices=ESTADO_CHOICES, default='A')

    def __str__(self):
        return self.nombre


class Comuna(models.Model):
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('I', 'Inactivo'),
    ]

    nombre = models.CharField(max_length=100)
    estado = models.CharField(
        max_length=1, choices=ESTADO_CHOICES, default='A')

    def __str__(self):
        return self.nombre

transporteescolar/establecimientos/forms.py
from django import forms
from .models import Establecimiento
from django.core.exceptions import ValidationError
import re


class EstablecimientoForm(forms.ModelForm):
    class Meta:
        model = Establecimiento
        fields = ['nombre', 'direccion', 'telefono', 'comuna', 'email']

    telefono = forms.CharField(
        max_length=9,
        help_text="Ingrese 9 dígitos"
    )

    def clean_telefono(self):
        telefono = self.cleaned_data.get('telefono')

        # Si el teléfono contiene +56, eliminar el prefijo para mostrar solo 9 dígitos en el formulario
        # if telefono.startswith('+56'):
        #    telefono = telefono[3:]

        # Validar que el teléfono tenga exactamente 9 dígitos
        if not re.match(r'^\d{9}$', telefono):
            raise ValidationError(
                "El número de teléfono debe tener 9 dígitos.")

        # Retornar el teléfono con el prefijo +56 agregado
        return telefono

transporteescolar/establecimientos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Establecimiento
from .forms import EstablecimientoForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test


@login_required(login_url="/usuarios/login")
@user_passes_test(lambda u: u.is_superuser)
def registrar_establecimiento(request):
    if request.method == 'POST':
        form = EstablecimientoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Establecimiento registrado exitosamente.')
            return redirect('establecimientos:listar_establecimientos')
    else:
        form = EstablecimientoForm()
    return render(request, 'establecimientos/registrar_establecimiento.html', {'form': form})


@login_required(login_url="/usuarios/login")
def listar_establecimientos(request):
    establecimientos = Establecimiento.objects.all()
    return render(request, 'establecimientos/listar_establecimientos.html', {'establecimientos': establecimientos})


@login_required(login_url="/usuarios/login")
@user_passes_test(lambda u: u.is_superuser)
def editar_establecimiento(request, id):
    establecimiento = get_object_or_404(Establecimiento, id=id)
    if request.method == 'POST':
        form = EstablecimientoForm(request.POST, instance=establecimiento)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Establecimiento actualizado exitosamente.')
            return redirect('establecimientos:listar_establecimientos')
    else:
        form = EstablecimientoForm(instance=establecimiento)
    return render(request, 'establecimientos/editar_establecimiento.html', {'form': form, 'establecimiento': establecimiento})


@login_required(login_url="/usuarios/login")
@user_passes_test(lambda u: u.is_superuser)
def eliminar_establecimiento(request, id):
    establecimiento = get_object_or_404(Establecimiento, id=id)
    if request.method == 'POST':
        establecimiento.delete()
        messages.success(request, 'Establecimiento eliminado exitosamente.')
        return redirect('establecimientos:listar_establecimientos')
    return render(request, 'establecimientos/eliminar_establecimiento.html', {'establecimiento': establecimiento})

transporteescolar/establecimientos/templates/establecimientos/editar_establecimiento.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Editar Establecimiento
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Editar Establecimiento</h1>
                <form action="{% url 'establecimientos:editar_establecimiento' establecimiento.id %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    
                    <center>
                        <button class="btn btn-success">Editar Establecimiento</button>
                        <a href="{% url 'establecimientos:listar_establecimientos' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}

transporteescolar/establecimientos/templates/establecimientos/eliminar_establecimiento.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Eliminar Establecimiento
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Eliminar Establecimiento</h1>
                <p>
                    <p>¿Estás seguro de que deseas eliminar el establecimiento {{ establecimiento.nombre }}?</p>
                </p>
                <form action="{% url 'establecimientos:eliminar_establecimiento' establecimiento.id %}"
                      method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-danger">Eliminar Establecimiento</button>
                        <a href="{% url 'establecimientos:listar_establecimientos' %}"
                           class="btn btn-secondary">Cancelar</a></center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}

transporteescolar/establecimientos/templates/establecimientos/listar_establecimientos.html
{% extends "base.html" %}
{% block title %}
  Listado de Establecimientos
{% endblock title %}
{% block content %}
  <div class="container">
    <h1>Listado de Establecimientos</h1>
    {% if user.is_superuser %}
      <button class="btn btn-primary mb-3"
              onclick="window.location.href='{% url 'establecimientos:registrar_establecimiento' %}'">
        Registrar Establecimiento
      </button>
    {% endif %}
    <div class="row">
      <table id="table"
             data-show-export="true"
             data-pagination="true"
             data-click-to-select="true"
             data-show-toggle="true"
             data-show-columns="true"
             data-search="true">
      </table>
    </div>
  </div>
  <script>
    var $table = $('#table')
    $(function () {
        function operateFormatter(value, row, index) {
          
            let editar =""
            let eliminar =""
            {% if user.is_superuser %}
              editar = '<button class="btn btn-warning btn-sm editar" href="javascript:void(0)" title="Editar">Editar</button>&nbsp;&nbsp;'
              eliminar = '<button class="btn btn-danger btn-sm eliminar" href="javascript:void(0)" title="Eliminar">Eliminar</button>&nbsp;&nbsp;'
            {% endif %}
            return [editar, eliminar].join('');
          }
        
          window.operateEvents = {
            'click .editar': function (e, value, row, index) {
                window.location.href = "{% url 'establecimientos:editar_establecimiento' 0 %}".replace('0', row.id);
            },
            'click .eliminar': function (e, value, row, index) {
                window.location.href = "{% url 'establecimientos:eliminar_establecimiento' 0 %}".replace('0', row.id);
            }
          }

      var data = [{% for establecimiento in establecimientos %}
        {   id:"{{ establecimiento.id }}",
            nombre:"{{ establecimiento.nombre }}",
            direccion:"{{ establecimiento.direccion }}",
            telefono: "{{ establecimiento.telefono }}",
            comuna: "{{ establecimiento.comuna.nombre }}",
            email: "{{ establecimiento.email }}",
            estado: "{{ establecimiento.get_estado_display }}",
            operate: "Detalle"
        },
        {% endfor %}
        ]


           function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
              height: 550,
              locale: "es-cl",
              data: data,
              classes:"table table-striped table-fit table-bordered table-hover",
              columns: [
                [{
                  field: 'id',
                  title: 'id',
                  visible: false,
                  align: 'center'
                },{
                    field: 'nombre',
                    title: 'Nombre',
                    visible: true,
                    align: 'center'
                  },{
                    field: 'direccion',
                    title: 'Dirección',
                    sortable: true,
                    align: 'center'
                  },{
                    field: 'comuna',
                    title: 'Comuna',
                    sortable: true,
                    align: 'center'
                  }
                  ,
                  {
                    field: 'telefono',
                    title: 'Teléfono',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'email',
                    title: 'Email',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'estado',
                    title: 'Estado',
                    sortable: true,
                    align: 'center'
                  },
                  {
                    field: 'operate',
                    title: 'Detalle',
                    align: 'center',
                    clickToSelect: false,
                    events: window.operateEvents,
                    formatter: operateFormatter
                    {% if not user.is_superuser %}
                    ,  visible: false,
                    {% endif %}
                  }
                ]
              ]
            })
          
        }

        
      
      initTable()
    })

  </script>
{% endblock content %}

transporteescolar/establecimientos/templates/establecimientos/registrar_establecimiento.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Registrar Establecimiento
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 justify-content-center align-items-center g-2">
                <h1>Registrar Establecimiento</h1>
                <form action="{% url 'establecimientos:registrar_establecimiento' %}"
                      method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <center>
                        <button class="btn btn-success ">Registrar Establecimiento</button>
                        <a href="{% url 'establecimientos:listar_establecimientos' %}"
                           class="btn btn-secondary">Cancelar</a>
                    </center>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
{% endblock content %}